version: "3.8"
networks:
    distnet:
        ipam:
            config:
              - subnet: 192.168.1.0/24
                gateway: 192.168.1.1 

services: 
    inventorydb:
        image: postgres:latest
        restart: always
        hostname: inventorydb
        networks:
            distnet:
                ipv4_address: 192.168.1.2
        environment:
            LISTEN_ADDRESSES: "*"
            POSTGRES_PASSWORD: password123
            POSTGRES_USER: inventoryuser
            POSTGRES_DB: inventorydb
    orderdb:
        image: postgres:latest
        restart: always
        hostname: orderdb
        networks:
            distnet:
                ipv4_address: 192.168.1.3
        environment:
            LISTEN_ADDRESSES: "*"
            POSTGRES_PASSWORD: password123
            POSTGRES_USER: orderuser
            POSTGRES_DB: orderdb
    inventory:
        image: inventory:latest
        networks:
            - distnet
        depends_on: 
            - "inventorydb"
        environment:
            INVENTORY_POSTGRES_HOST: 192.168.1.2
        deploy:
            mode: replicated
            replicas: 3
        healthcheck:
            test: ["CMD", "curl", "http://localhost:8090/actuator/health"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 10s  
    order:
        image: order:latest
        networks:
            - distnet
        depends_on:
            - "orderdb"
        ports:
            - "3001:3001"
        environment:
            - NODE_ENV=composed
            - ORDER_POSTGRES_HOST=192.168.1.3
            - DEV_PORT=3001
            - POSTGRES_USER=orderuser
            - POSTGRES_PASSWORD=password123
            - INVENTORY_URL=http://nginx:9000
        deploy:
            replicas: 1
    front:
        image: front:latest
        networks:
            - distnet
        ports:
            - "3000:3000"
        deploy:
            replicas: 1
    nginx:
        image: nginx:latest
        networks:
            - distnet
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - inventory
        ports:
            - "9000:9000"
        